### ISSUE TITLE
Filter out data points with invalid GPS and/or Radiation reading

### ISSUE THREAD

**Issue by nokton** [Safecast/safecastapi#112] opened 2013-04-30 19:16 UTC
Based on A/V field for GPS and Radiation level, filter out from output file.

These values records should still be stored in the database with the validity flags, but not be passed on to the master out put file.

On maps in the api map previewer these should be marked differently so it's easy to see these are invalid data points.

**Comment by matschaffer** [comment] 2019-03-27 01:46
https://github.com/Safecast/safecastapi/blob/master/app/models/bgeigie_import.rb#L188 is the code in question. It checks for A or V, but doesn't store the value only discards the line if it's something other than A or V.

**Comment by matschaffer** [comment] 2019-03-27 02:02
Closing as duplicate of #495

**Closed by matschaffer** 2019-03-27 02:02 UTC
Labels: backlog, bug

**Comment by nokton** [comment] 2019-03-28 09:01
Hi Mat,

Can you explain why we’re doing this and from what this is being filtered out of?

Best,
Pieter

**Comment by matschaffer** [comment] 2019-03-28 09:07
No, the code predates me so can't say why. The import process just doesn't write the values to the db afaict
