### ISSUE TITLE
Severe bug in Bgeigie Import viewer! Imports are incorrectly rejected because of false high values

### ISSUE THREAD

**Issue by fobrs** [Safecast/safecastapi#706] opened 2020-07-01 21:10 UTC
If you look at this import:  https://api.safecast.org/en-US/bgeigie_imports/39752

You are greeted with a message that this import contains high values:
`Attention! This log file contains: 「A possible radiological anomaly. Max µSv/h: 0.68.」`
The moderator writes:
```
Comment
Moderator comment: Holding approval pending confirmation of high dose rates.
```

But at the same time there is displayed:
```
Highest Measurement
124
```
This last values is correct if you examine the actual LOG data. 124 CPM is 0.37 µSv/h

So where comes the Max µSv/h: 0.68 from?

Could it be that a lot of imports are incorrectly rejected because of this? 

Another example.

My own import: https://api.safecast.org/en-US/bgeigie_imports/47818 has strange high values too.
Max is 108 CPM ( 0.32 µSv/h)

But in the following image the selected measurement has 156 CPM. But the actual line in the LOG file of this point shows 106 CPM:
```
$BNRDD,2735,2020-06-29T10:42:11Z,106,13,1769,A,5313.0698,N,00633.5683,E,-6.30,A,9,91*54
```
(text continues after image)

![image](https://user-images.githubusercontent.com/37036753/86290367-a9490680-bbed-11ea-8560-748f976c4437.png)

The Log File Stats in the next image are incorrect too. Max value was 108 but in the image 156 CMP is shown as max.

![image](https://user-images.githubusercontent.com/37036753/86291011-ae5a8580-bbee-11ea-8715-24241fb28661.png)

**Comment by sasharevzin** [comment] 2020-07-01 22:11
@matschaffer @auspicacious from ruby code perspective I didn't find anything wrong. would take a look?

**Comment by matschaffer** [comment] 2020-07-01 22:16
The viewer is JS - @Frangible can probably confirm but I suspect there’s a cp5s causing the anomaly alert.

**Comment by fobrs** [comment] 2020-07-02 08:04
Yes, the use of the cp5s value at those points in the viewer is the problem. When LOG data is imported in your database however, the cp5s values are not used.

**Comment by Frangible** [comment] 2020-07-02 14:20
This is by design and not a bug.  Note that the viewer’s log checking is a displayed advisory of anomalies detected only, and it’s up to the moderator reviewing the log whether they interpret the anomaly as bad/invalid data or not.

Also, a high cp5s reading is not a “false” high value.  It is data collected by the instrument.  While other layers of the API may only use an avaerage, an error in a cp5s will still cause elevated measurements for the time period it is being integrated into.  These elevated averaged values may not be above an error threshold, but it is still enough to introduce and error and reduce the precision and accuracy of the dataset if that high cp5s value shifts others to be statistically significantly higher than they truly are.  This introduces error and variance into the dataset as a whole and is not ideal.

**Comment by fobrs** [comment] 2020-07-02 15:18
I think it's a 'false high' if you multiply the cp5s value by 12 and take that as the CMP value of a measurement.

**Comment by anaavu** [comment] 2020-07-02 17:51
We noticed the same discrepancy, but it was our impression that the values on the viewer were the correct ones, while due to a conversion problem with cp5s to CPM, they don't show up on the log files properly. It would be great if someone can clarify!

**Comment by juhele** [comment] 2020-07-03 07:22
Hi,
I do not see any problem with Safecast API or the data. I downloaded the data and displayed them:

![bGeigie_29121222log_QGIS1](https://user-images.githubusercontent.com/1697788/86439495-f241ad80-bd08-11ea-8aac-a76f8daca94d.jpg)

![bGeigie_29121222log_QGIS2](https://user-images.githubusercontent.com/1697788/86439613-32089500-bd09-11ea-8f3c-ced9193ac497.png)

The values are slightly higher and there is one over 0.5 microSv/h so I understand that visual alert. Does not say it is dangerous or man-made anomaly - most of the anomalies are natural or related with natural materials. Looks like Nairobi just has higher natural bacground - information about local geology might tell you more.

But you can find such anomalies also in Europe - Roma (Italy) has higher natural background and this anomaly is in Berlin, for example:
https://api.safecast.org/en-US/bgeigie_imports/47045

**Comment by seanbonner** [comment] 2020-07-03 09:09
As it appears everything is working as designed and it was just a misunderstanding of the design goals I'm going to close this.

**Closed by seanbonner** 2020-07-03 09:09 UTC
